#pragma once
// Undefines all defines used in nimbase
#undef N_INLINE
#undef NIM_CONST
#undef NIM_THREADVAR
#undef NIM_THREAD_LOCAL
#undef NIM_EXTERNC
#undef N_LIB_PRIVATE
#undef N_CDECL
#undef N_STDCALL
#undef N_SYSCALL
#undef N_FASTCALL
#undef N_THISCALL
#undef N_SAFECALL
#undef N_CDECL_PTR
#undef N_STDCALL_PTR
#undef N_SYSCALL_PTR
#undef N_FASTCALL_PTR
#undef N_THISCALL_PTR
#undef N_SAFECALL_PTR
#undef N_CLOSURE
#undef N_CLOSURE_PTR
#undef N_NOCONV
#undef N_NOCONV_PTR
#undef N_NOINLINE
#undef N_NOINLINE_PTR
#undef N_NIMCALL
#undef N_NIMCALL_PTR
#undef N_RAW_NIMCALL
#undef N_LIB_IMPORT
#undef N_LIB_EXPORT
#undef N_LIB_EXPORT_VAR
#undef NIM_INTBITS
#undef USE_NIM_NAMESPACE
#undef HAVE_STDINT_H
#undef HAVE_CSTDINT
#undef SEQ_DECL_SIZE
