#
# C/C++ interop
#
# Generates a C++ header that includes the Nim compiler generated header.
# The header generator allows for the exporting of constants to either a
# C++ constexpr variable or a preprocessor define.
#
# Also included is a String wrapper type for nim strings, so that the frontend
# can easily access nim strings without needing a conversion to a `cstring`
#

import
  std/[compilesettings, enumutils, macros, os, strformat, with],
  ./interop/macroutils

type
  ccstring* {. importc: "const char *" .} = distinct cstring
    ## Immutable version of cstring
    ##

  HasPrivateData* = concept a
    ## Concept for a type that is an object that has a private data field.
    ##
    a is object
    a.pd is object|tuple

template `@`*[T: HasPrivateData](o: T): auto =
  ## Shortcut for accessing the private data in an object
  ## 
  o.pd

# Header generation ===========================================================

type
  Header = object
    defines: string
    vars: string
    aliases: string

{.push compileTime .}

func intToC(bytes: int; isSigned: bool): string = 
  result.add('N')
  result.add(if isSigned: 'I' else: 'U')
  result.add($(bytes * 8))

func toC(T: typedesc[SomeInteger]): string =
  ## Get the nimbase type name of the given integer type.
  ##
  result = intToC(sizeof(T), T is SomeSignedInt)

func toC(T: typedesc[SomeFloat]): string =
  ## Get the nimbase type name for the given float type.
  ##
  result = &"NF{sizeof(T) * 8}"

proc alias*(h: var Header; ident, expression: string; ) =
  ## Adds a type alias (using declaration) to the header with the given
  ## identifier and type expression. The expression and identifier must
  ## be valid C++ code.
  ## 
  h.aliases.add(&"using {ident} = {expression};\n")

proc constexpr*(h: var Header; name, typeEx, valueEx: string; ) =
  ## Adds a constexpr variable to the header with the given name,
  ## type and value expression, which must be valid C++ code.
  ##
  h.vars.add(&"static constexpr {typeEx} {name} = {valueEx};\n")

proc constexpr*(h: var Header; name: string; value: SomeInteger)  =
  ## Adds a constexpr variable with name set to the given Nim integer value
  ## 
  constexpr(h, name, toC(typeOf(value)), $value)

proc constexpr*(h: var Header; name: string; R: typedesc[range]) =
  ## Adds lower and upper bounds of the range as constexpr variables.
  ## 
  constexpr(h, name & "Low", low(R))
  constexpr(h, name & "High", high(R))

proc addEnum*(h: var Header; E: typedesc[enum]; foreign = false) =
  ## Adds a Nim enum to the header. A type alias is created for the enum's
  ## underlying ordinal type, and a constexpr variable is added for each
  ## member of the enum.
  ## 
  ## If `foreign` is true then `B` is prefixed to the name of the type alias.
  ## 
  var name: string
  if foreign:
    name.add("B")
  name.add($E)
  let ctype = intToC(sizeof(E), false)
  alias(h, name, ctype)
  for e in E:
    constexpr(h, symbolName(e), name, $ord(e))
  constexpr(h, $E & "Low", ctype, $ord(low(E)))
  constexpr(h, $E & "High", ctype, $ord(high(E)))

proc define*(h: var Header; name, value: string; ) =
  ## Adds a preprocessor definition with the given name and value.
  ## 
  h.defines.add(&"#define {name} {value}\n")

proc define*(h: var Header; name, typing, value: string; ) =
  ## Adds a preprocessor definition with value type casted using a C-style cast.
  ## 
  define(h, name, &"((typing)value)")

{.pop.}

var 
  headerCache {.compileTime.}: Header

template header*(body) =
  ## Add content to the generated header
  ## Things you can add:
  ##  - constexpr variables
  ##  - Preprocessor defines
  ##  - Type aliases
  ## 
  ## Only the procs with the first parameter being `var Header` can be used in
  ## `body`
  ##
  static:
    with headerCache:
      body


const
  headerTmpl = """
#pragma once

#include "tbb_nim.h"
#include "unnimbase.h"

// Nim-generated defines
$headerCache.defines@

// Nim-generated variables
$headerCache.aliases@

namespace B {
$headerCache.vars@
}

"""

  nimcacheDir = querySetting(SingleValueSetting.nimcacheDir)
  headerPath = nimcacheDir / "tbb.hxx"

proc writeHeaderImpl() {.compileTime.} =
  writeFile(headerPath, fmt(headerTmpl, '$', '@'))

template writeHeader*() =
  ## Generates the header in the nimcache directory with name tbb.hxx
  ## The header includes the header generated by the nim compiler
  ##
  static:
    writeHeaderImpl()

# C++ Interop =================================================================

{. push compileTime .}
  
proc frontImpl(name: string; node: NimNode) =
  # adds pragmas specified by [front]
  expectKind(node, nnkProcDef)
  if name == "":
    node.addPragma(ident("exportcpp"))
  else:
    node.addColonPragma("exportcpp", name)
  node.addPragma(ident("used"))
  node.addColonPragma("raises", newTree(nnkBracket))

{. pop .}

# C++ export ==================================================================

import ./interop/members
export members

macro front*(procDef) =
  ## Custom pragma that makes procs available to the front end.
  ## 
  ## The proc declaration is modified to have the following pragmas:
  ##  * `exportcpp`
  ##  * `used`
  ##  * `raises: []`
  ##
  frontImpl("", procDef)
  result = procDef

macro frontx*(name: static string; procDef) =
  ## Same as [front] but allows you to specify the name passed to exportc
  ##
  frontImpl(name, procDef)
  result = procDef

# String interop

proc bInitString*(): string {.front.} =
  result = ""

proc bInitString*(len: int): string {.front.} =
  result = newString(len)

proc bInitString*(str: ccstring): string {.front.} =
  result = $(cstring(str))

proc bInitString*(str: string): string {.front.} =
  result = str

proc bDestroy*(s: string) {.front.} =
  `=destroy`(s)

proc stringReset*(s: var string) {.frontx: "bReset".} =
  s = ""

proc stringAdd*(s: var string; ch: char) {.frontx: "bAdd".} =
  s.add(ch)

proc data*(s: string): ccstring {.front.} =
  result = s.ccstring

const stringCodegen = """
struct $1 {
  $2
$1(NimStringV2 s);
$1($1 const& str);
$1($1 &&str);
~$1();
$1& operator=($1 const& str);
$1& operator=($1 &&str);
};
"""

type
  BString {.exportc, codegenDecl: stringCodegen.} = object
    s*: string

{. emit: """

BString::BString(NimStringV2 s) :
    s(s) 
{
}

BString::BString(BString const& str) :
    s(bInitString(str.s))
{
}

BString::BString(BString &&str) :
    s(str.s) 
{ 
    bReset(str.s);
}

BString::~BString() {
    bReset(s);
}

BString& BString::operator=(BString const& str) {
    bReset(s);
    s = bInitString(str.s);
    return *this;
}

BString& BString::operator=(BString &&str) {
    auto tmp = s;
    s = str.s;
    str.s = tmp;
    bReset(str.s);
    return *this;
}

""".}
