#
# C header generation utils
#

import
  std/[compilesettings, os, strformat]


func toC(T: typedesc[SomeInteger]): string =
  result = "N"
  when T is SomeSignedInt:
    result.add('I')
  else:
    result.add('U')
  when T isnot int|uint:
    result.add($(sizeof(T) * 8))
  
var 
  defines {.compileTime.}: string
  vars {.compileTime.}: string

{. push compileTime .}

proc define*(name: string; value: string) =
  defines.add(&"#define {name} {value}\n")

proc typedDefine*(name, typing, value: string; ) =
  define(name, &"(({typing}){value})")

proc define*(name: string; value: SomeInteger) =
  typedDefine(name, toC(typeOf(value)), $value)

proc define*(name: string; R: typedesc[range]) =
  define(name & "Low", low(R))
  define(name & "High", high(R))

proc constvar*(name, typeExpr, valExpr: string;) =
  vars.add(&"static constexpr {typeExpr} {name} = {valExpr};\n")

proc constvar*(name: string; value: SomeInteger) =
  constvar(name, toC(typeOf(value)), $value)

proc constvar*(name: string; R: typedesc[range]) =
  constvar(name & "Low", low(R))
  constvar(name & "High", high(R))

const 
  headerTmpl = """
#pragma once
#include "tbb_nim.h"

{defines}

namespace B {{

{vars}

}}
"""

  nimcacheDir = querySetting(SingleValueSetting.nimcacheDir)
  headerPath = nimcacheDir / "tbb.h"

proc writeHeader*() =
  ## Generates the header in the nimcache directory with name tbb.h
  ## The header includes the header generated by the nim compiler
  var header = fmt(headerTmpl)
  writeFile(headerPath, header)

{. pop .}
