#
# C/C++ interop
#
# Generates a C++ header that includes the Nim compiler generated header.
# The header generator allows for the exporting of constants to either a
# C++ constexpr variable or a preprocessor define.
#
# Also included is a String wrapper type for nim strings, so that the frontend
# can easily access nim strings without needing a conversion to a `cstring`
#

import
  std/[compilesettings, macros, os, strformat]

type
  ccstring* {. importc: "const char *" .} = distinct cstring
    ## Immutable version of cstring
    ##

func toC(T: typedesc[SomeInteger]): string =
  ## Get the nimbase type name of the given integer type.
  ##
  result.add('N')
  when T is SomeSignedInt:
    result.add('I')
  else:
    result.add('U')
  result.add($(sizeof(T) * 8))

func toC(T: typedesc[SomeFloat]): string =
  ## Get the nimbase type name for the given float type.
  ##
  result = &"NF{sizeof(T) * 8}"

  
var 
  defines {.compileTime.}: string
  vars {.compileTime.}: string

{. push compileTime .}

proc define*(name: string; value: string) =
  defines.add(&"#define {name} {value}\n")

proc typedDefine*(name, typing, value: string; ) =
  define(name, &"(({typing}){value})")

proc define*(name: string; value: SomeInteger) =
  typedDefine(name, toC(typeOf(value)), $value)

proc define*(name: string; R: typedesc[range]) =
  define(name & "Low", low(R))
  define(name & "High", high(R))

proc constvar*(name, typeExpr, valExpr: string;) =
  vars.add(&"static constexpr {typeExpr} {name} = {valExpr};\n")

proc constvar*(name: string; value: SomeInteger) =
  constvar(name, toC(typeOf(value)), $value)

proc constvar*(name: string; R: typedesc[range]) =
  constvar(name & "Low", low(R))
  constvar(name & "High", high(R))

template frontRef*(T: typedesc[ref]) {.dirty.} =
  proc `ref`*(x: T) {.front.} =
    GcRef(x)
  proc unref*(x: T) {.front.} =
    GcUnref(x)

template frontDestroy*(T: typedesc[object|tuple]) {.dirty.} =
  proc destroy*(x: ptr T) {.front.} =
    `=destroy`(x[])

const 
  headerTmpl = """
#pragma once

#include "tbb_nim.h"
#include "unnimbase.h"

// Nim-generated defines
$defines@

namespace B {
// Nim-generated variables
$vars@
}

"""

  nimcacheDir = querySetting(SingleValueSetting.nimcacheDir)
  headerPath = nimcacheDir / "tbb.hxx"

proc writeHeader*() =
  ## Generates the header in the nimcache directory with name tbb.hxx
  ## The header includes the header generated by the nim compiler
  ##
  var header = fmt(headerTmpl, '$', '@')
  writeFile(headerPath, header)

proc frontImpl(name: string; node: NimNode): NimNode =
  expectKind(node, nnkProcDef)
  if name == "":
    node.addPragma(ident("exportcpp"))
  else:
    node.addPragma(newTree(nnkExprColonExpr, ident("exportcpp"), newLit(name)))
  node.addPragma(ident("used"))
  node.addPragma(newTree(nnkExprColonExpr, ident("raises"), newTree(nnkBracket)))
  result = node
  

{. pop .}

macro front*(procDef) =
  ## Custom pragma that makes procs available to the front end.
  ## 
  ## The proc declaration is modified to have the following pragmas:
  ##  * `exportcpp`
  ##  * `used`
  ##  * `raises: []`
  ##
  result = frontImpl("", procDef)

macro frontx*(name: static string; procDef) =
  ## Same as [front] but allows you to specify the name passed to exportc
  ##
  result = frontImpl(name, procDef)

# String interop

proc initString*(): string {.front.} =
  result = ""

proc initString*(len: int): string {.front.} =
  result = newString(len)

proc initString*(str: ccstring): string {.front.} =
  result = $(cstring(str))

proc initString*(str: string): string {.front.} =
  result = str

proc destroy*(s: string) {.front.} =
  `=destroy`(s)

proc stringReset*(s: var string) {.frontx: "reset".} =
  s = ""

proc stringAdd*(s: var string; ch: char) {.frontx: "add".} =
  s.add(ch)

proc data*(s: string): ccstring {.front.} =
  result = s.ccstring

const stringCodegen = """
struct $1 {
  $2
$1(NimStringV2 s);
$1($1 const& str);
$1($1 &&str);
~$1();
$1& operator=($1 const& str);
$1& operator=($1 &&str);
};
"""

type
  String {.exportc, codegenDecl: stringCodegen.} = object
    s*: string

{. emit: """

String::String(NimStringV2 s) :
    s(s) 
{
}

String::String(String const& str) :
    s(initString(str.s)) 
{
}

String::String(String &&str) : 
    s(str.s) 
{ 
    reset(str.s); 
}

String::~String() { 
    reset(s); 
}

String& String::operator=(String const& str) {
    reset(s);
    s = initString(str.s);
    return *this;
}

String& String::operator=(String &&str) {
    auto tmp = s;
    s = str.s;
    str.s = tmp;
    reset(str.s);
    return *this;
}

""".}