#
# C/C++ interop
#

import
  std/[compilesettings, macros, os, strformat]


func toC(T: typedesc[SomeInteger]): string =
  result.add('N')
  when T is SomeSignedInt:
    result.add('I')
  else:
    result.add('U')
  result.add($(sizeof(T) * 8))

func toC(T: typedesc[SomeFloat]): string =
  result = &"NF{sizeof(T) * 8}"

  
var 
  defines {.compileTime.}: string
  vars {.compileTime.}: string

{. push compileTime .}

proc define*(name: string; value: string) =
  defines.add(&"#define {name} {value}\n")

proc typedDefine*(name, typing, value: string; ) =
  define(name, &"(({typing}){value})")

proc define*(name: string; value: SomeInteger) =
  typedDefine(name, toC(typeOf(value)), $value)

proc define*(name: string; R: typedesc[range]) =
  define(name & "Low", low(R))
  define(name & "High", high(R))

proc constvar*(name, typeExpr, valExpr: string;) =
  vars.add(&"static constexpr {typeExpr} {name} = {valExpr};\n")

proc constvar*(name: string; value: SomeInteger) =
  constvar(name, toC(typeOf(value)), $value)

proc constvar*(name: string; R: typedesc[range]) =
  constvar(name & "Low", low(R))
  constvar(name & "High", high(R))

template frontRef*(T: typedesc[ref]) {.dirty.} =
  proc `ref`*(x: T) {.front.} =
    GcRef(x)
  proc unref*(x: T) {.front.} =
    GcUnref(x)

template frontDestroy*(T: typedesc[object|tuple]) {.dirty.} =
  proc destroy*(x: ptr T) {.front.} =
    `=destroy`(x[])

const 
  headerTmpl = """
#pragma once

#include "tbb_nim.h"
#include "unnimbase.h"

// Nim-generated defines
$defines@

namespace B {
// Nim-generated variables
$vars@
}

"""

  nimcacheDir = querySetting(SingleValueSetting.nimcacheDir)
  headerPath = nimcacheDir / "tbb.hxx"

proc writeHeader*() =
  ## Generates the header in the nimcache directory with name tbb.h
  ## The header includes the header generated by the nim compiler
  var header = fmt(headerTmpl, '$', '@')
  writeFile(headerPath, header)

proc frontImpl(name: string; node: NimNode): NimNode =
  expectKind(node, nnkProcDef)
  if name == "":
    node.addPragma(ident("exportcpp"))
  else:
    node.addPragma(newTree(nnkExprColonExpr, ident("exportcpp"), newLit(name)))
  node.addPragma(ident("used"))
  node.addPragma(newTree(nnkExprColonExpr, ident("raises"), newTree(nnkBracket)))
  result = node
  

{. pop .}

macro front*(procDef) =
  ## Custom pragma that makes procs available to the front end.
  ##
  result = frontImpl("", procDef)

macro frontx*(name: static string; procDef) =
  ## Same as [front] but allows you to specify the name passed to exportc
  ##
  result = frontImpl(name, procDef)
